activity/urls.py
from django.urls import path
from .views import *

app_name = 'activity'

urlpatterns = [
    path('', main_activity),
    path('ejercicios/', exercises_create),
    path('categorias/',category_create),
    path('rutinas/',rutine_create),
    path('delete_exercise/<int:id>/', delete_exercise, name="delete_exercise"),
    path('update_exercise/<int:id>/', update_exercise, name="update_exercise"),
    path('change_exercise/<int:id>/', change_exercise, name="change_exercise"),
]

work/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('activity.urls'))
]

activity/models.py
from django.db import models

class User(models.Model): #Usuarios
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()

class Category (models.Model): #Categoria gym, calistenia, cardio...
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Exercises (models.Model): #Tabla de ejercicios
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Rutine (models.Model): #Pecho, espalda, brazo...
    name = models.CharField(max_length=30)
    exercises = models.ManyToManyField(Exercises)
    repetitions = models.IntegerField(default=0)
    series = models.IntegerField(default=0)
    description = models.CharField(max_length=150)
    def __str__(self):
        return self.name

class Register (models.Model): #Registros de actividad
    date = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

activity/forms.py
from django import forms
from .models import *

class catgo_Form(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class exer_Form(forms.ModelForm):
    class Meta:
        model = Exercises
        fields = '__all__'

class ruti_Form(forms.ModelForm):
    class Meta:
        model = Rutine
        fields = ('name','description')

activity/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .forms import *
from .models import *

# INSTRUCCIONES PARA EL TEMPLATE PRINCIPAL
def main_activity (request):
    exercises = Exercises.objects.all()
    rutines = Rutine.objects.all()
    context = {
        'exercises':exercises,
        'rutines':rutines,
    }
    return render(request,'main.html', context)



# INSTRUCCIONES PARA EL TEMPLATE EJERCICIOS
def exercises_create (request):
    list = Category.objects.all()
    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']
        category_id = request.POST['category']
        try:
            category = Category.objects.get(pk=category_id)
        except Category.DoesNotExist:
            category = None
        Exercises.objects.create(name=name,description=description,category=category)
        return redirect('/')
    return render(request, 'exercises.html',{'list': list})

# INSTRUCCIONES PARA ELIMINAR EJERCICIOS
def delete_exercise (request, id):
    register = Exercises.objects.get(pk=id)
    register.delete()
    return redirect('/')

def update_exercise (request,id):
    exercise = Exercises.objects.get(pk=id)
    category = Category.objects.all()
    return render(request,'update_exercise.html',{'exercise':exercise,'category':category})

def change_exercise(request, id):
    exercise = Exercises.objects.get(pk=id)
    name = request.POST['name']
    description = request.POST['description']
    category_id = request.POST['category']
    try:
        category = Category.objects.get(pk=category_id)
    except Category.DoesNotExist:
        category = None
    exercise.name = name
    exercise.description = description
    exercise.category = category
    exercise.save()
    return redirect('/')

# INSTRUCCIONES PARA EL TEMPLATE CATEGORIA
def category_create(request):
    formset = catgo_Form()
    if request.method == 'POST':
        formset = catgo_Form(request.POST)
        if formset.is_valid():
            formset.save()
        else:
            print(formset.errors)
    context = {
        'formset' : formset
    }
    return render(request, 'category.html',context)


# INSTRUCCIONES PARA EL TEMPLATE RUTINAS
def rutine_create (request):
    if request.method == 'POST':
        form = ruti_Form(request.POST)
        if form.is_valid():
            rutine = form.save(commit=False)
            rutine.save()
            exercises_list = request.POST.getlist('exercises')
            for exercise_id in exercises_list:
                exercise = Exercises.objects.get(pk=exercise_id)
                rutine.exercises.add(exercise)
    else:
        form = ruti_Form()
    exercises = Exercises.objects.all()
    return render(request,'rutine.html', {'form': form, 'exercises': exercises})

activity/templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorias</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <h1>Crear nueva categoria</h1>
        {{ formset.as_p }}
        <input type="submit">
    </form>
</body>
</html>

activity/templates/exercises.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ejercicios</title>
</head>
<body>
    <form id="myForm" method="post">
        {% csrf_token %}
        <label>Nombre</label>
        <input type="text" name="name">
        <label>Descripción</label>
        <input type="text" name="description">
        <select name="category">
            <option selected>Categoria</option>
            {% for category in list %}
            <option value="{{category.id}}">{{category.name}}</option>
            {%endfor%}
        </select>
        <input type="submit" value="Guardar"/>
    </form>
</body>
<script>
</script>
</html>

activity/templates/header.html
{% load static %}
<html lang="en">
<head>
    <title>{% block tittle %}HEADER{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    <!--EL SIGUIENTE NAV CORRESPONDE AL HEADER, PUEDES MANIPULARLO Y/O CAMBIARLO PARA HACER EL LOGIN A TU GUSTO-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown link</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <br>
    {% block content %}
    {% endblock %}
</body>
</html>

activity/templates/main.html
{% extends "header.html" %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        {% block tittle %}Actividad{% endblock %}
    </head>
    <body>
        {% block content %}
        <!--TABLA DE EJERCICIOS-->
        <div class="container">
            <div class="row justify-content-md-center">
                <h5>Lista de ejercicios</h5>
                <br>
                <br>
                <h2>TABLA DE EJERCICIOS</h2>
                <div class="col-sm-12 col-md-12 col-xl-12 col-lg-12">
                    <div class="table-responsive">
                        <table id="exercise_table" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Descripcion</th>
                                    <th>Categoria</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for exercise in exercises %}
                                <tr>
                                    <td>{{ exercise.name }}</td>
                                    <td>{{ exercise.description }}</td>
                                    <td>{{ exercise.category.name }}</td>
                                    <td>
                                        <form action="{% url 'activity:delete_exercise' exercise.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger">
                                                <i>Eliminar</i>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/><path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/></svg>
                                            </button>
                                        </form>
                                        <form action="{%url 'activity:update_exercise' exercise.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-info">
                                                <i>Editar</i>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16" >
                                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                                                </svg>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <button onclick="window.location.replace('/ejercicios')">Agregar nuevo ejercicio</button>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <div class="container">
            <div class="row justify-content-md-center">
                <h2>TABLA DE CATEGORIAS</h2>
                <div class="col-sm-12 col-md-12 col-xl-12 col-lg-12">
                    <div class="table-responsive">
                        <table id="rutine_table" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Ejercicios</th>
                                    <th>Descripción</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for rutine in rutines %}
                                <tr>
                                    <td>{{rutine.name}}</td>
                                    <td>{{rutine.exercises.name}}</td>
                                    <td>{{rutine.description}}</td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script>
            $(document).ready(function() {
                $('#exercise_table').DataTable();
            });
            $(document).ready(function() {
                $('#rutine_table').DataTable();
            });
        </script>
        {% endblock %}
    </body>
</html>

activity/templates/rutine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rutinas</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <h1>Crear una nueva rutina</h1>
        {{ form.as_p }}
        <ul>
            <p>SELECCIONA LOS EJERCICIOS QUE DESEAS AGREGAR A ESTA RUTINA:</p>
            {% for exercise in exercises %}
                <li>
                    <label>
                        <input type="checkbox" name="exercises" value="{{ exercise.id }}">{{ exercise.name }}</label>
                </li>
            {% endfor %}
        </ul>
        <input type="submit" value="Guardar">
    </form>
</body>
</html>

activity/templates/update_exercise.html
{% extends "header.html" %}
{% load static %}
<head>
    {% block tittle %}Editar ejercicio{% endblock %}
</head>
{% block content %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <div class="card" style="background-color: #77aaa6;">
            <div class="card_body">
                <form action="{% url 'activity:change_exercise' exercise.id %}" method="post">{% csrf_token %}
                    <div class="card-header text-center">NOMBRE:
                        <div class="form-group"><input type="text" class="form-control" value="{{exercise.name}}" name="name"></div>
                    </div>
                    <div class="card-header text-center">DESCRIPCIÓN:
                        <div class="form-group"><input type="text" class="form-control" value="{{exercise.description}}" name="description"></div>
                    </div>
                    <div class="card-header text-center">CATEGORIA:
                        <div class="form-group">
                            <select name="category" id="" class="form-select">
                                <option value="" readonly>{{exercise.category}}</option>
                                {%for cat in category%}
                                <option value="{{cat.id}}">{{cat.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group text-center"><button type="submit" class="btn btn-success btn-block">Actualizar</button></div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock%}